/**
 * script.js - Interactive elements for the Data Analytics Dashboard
 */

function refreshData() {
    const btn = document.querySelector('.btn.primary');
    const originalText = btn.innerHTML;
    
    // Add loading animation to button
    btn.innerHTML = `<svg width="20" height="20" viewBox="0 0 24 24" fill="none" class="spin" style="animation: spin 1s linear infinite"><path d="M12 2v4m0 12v4M4.93 4.93l2.83 2.83m8.48 8.48l2.83 2.83M2 12h4m12 0h4M4.93 19.07l2.83-2.83m8.48-8.48l2.83-2.83" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg> Updating Pipeline...`;
    
    const styleSheet = document.createElement("style");
    styleSheet.innerText = `@keyframes spin { 100% { transform: rotate(360deg); } }`;
    document.head.appendChild(styleSheet);
    
    // Simulate backend fetch & response latency
    setTimeout(() => {
        
        // Anti-caching query param to visibly "refresh" the images generated by our Python backend
        const timestamp = new Date().getTime();
        
        const salesImg = document.getElementById('salesTrendImg');
        const categoryImg = document.getElementById('categoryDistImg');
        
        if (salesImg && categoryImg) {
            const updateImageRef = (imgElement) => {
                const currentSrc = imgElement.getAttribute('src').split('?')[0];
                imgElement.setAttribute('src', `${currentSrc}?t=${timestamp}`);
            }
            updateImageRef(salesImg);
            updateImageRef(categoryImg);
        }

        // Animate metric text values dynamically to indicate flush
        const metricValues = document.querySelectorAll('.metric-value');
        metricValues.forEach(el => {
            el.style.transform = "scale(1.15) translateY(-5px)";
            el.style.color = "#34d399";
            
            setTimeout(() => {
                el.style.transform = "";
                el.style.color = "";
            }, 350);
        });

        // Completion state for button
        btn.innerHTML = `<svg fill="none" stroke="currentColor" viewBox="0 0 24 24" width="20" height="20"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg> Data Synchronized!`;
        btn.style.background = "linear-gradient(135deg, #10b981, #059669)";
        btn.style.borderColor = "#34d399";
        
        // Revert button back to normal state
        setTimeout(() => {
            btn.innerHTML = originalText;
            btn.style.background = "";
            btn.style.borderColor = "";
        }, 3000);
        
    }, 1200);
}
